### ISSUE TITLE
Review of basic text content

### ISSUE THREAD

**Issue by jenweber** [ember-learn/the-shortest-ember-book#3]
I'm looking for volunteers who can answer a few questions about the impressions they have as they read the "book" and the content that's present. The "final" version will have fun images and code snippets on each page. Pretend they are there :P

Temporarily deployed to a slow, free [heroku endpoint](https://cherry-shortcake-43271.herokuapp.com/). Give it a sec to load.

**Questions**
- Who do you think the target audience is?
- What does someone get out of reading this?
- What might someone's impression of Ember be after reading this?
- Is anything missing?

**Comment by amyrlam** [comment]
> Who do you think the target audience is?

Developers who probably haven't used Ember before. Developers who are checking out emberjs.com documentation, could be new or experienced.

> What does someone get out of reading this?

Ember "at a glance"!

> What might someone's impression of Ember be after reading this?

It's stable. It's friendly. 

> Is anything missing?
Seems good so far!

**Comment by sivakumar-kailasam** [comment]
> Who do you think the target audience is?

Devs who have experience using another JS framework who don't know anything about ember except its name and that LinkedIn uses it 😅 

> What does someone get out of reading this?

Learn quick concepts & understand what's different about ember that they don't have in the framework of their choice.

> What might someone's impression of Ember be after reading this?

• Most framework concepts & cli are similar to what they know from their framework.
• The development & roadmap process seems to be community friendly.
• EmberObserver & Ember Data sound like great ideas to checkout

> Is anything missing?

• In RFCs may be we could mention that those who propose RFC don't need to implement it([link](https://emberjs.github.io/rfcs/introduction.html#implementing-an-rfc)). That was an exciting fact when I got introduced to it.
• Standard file layout for apps & libraries? That it helps ember devs get into any ember codebase, be aware of where things are, how they work & make changes right away. React devs might find this interesting since they don't have an agreed way of doing this :)
